#!/usr/bin/env bash
# Twins of the pipeline roles on another model: .claude/agents/<role>-saving.md.
# The /feature-saving command calls them; the regular /feature keeps calling the originals.
#
# Why separate files and not a launch flag: a subagent's model is taken ONLY from the
# role's front-matter. Verified 2026-09-06 against the transcripts — with
# CLAUDE_CODE_SUBAGENT_MODEL=claude-opus-5 and a hook stripping `model` from the Agent
# call, one role ran on claude-opus-5 while code-reviewer ran on claude-fable-5-1,
# i.e. the front-matter wins. So "the same pipeline on another model" means a second
# set of role files.
#
# The originals are the single source of truth: the twins are regenerated in full, and
# edits made in them are lost.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

ROLES=(requirement-analyst spec-writer rust-developer code-reviewer test-engineer)
AGENTS=".claude/agents"
SUFFIX="saving"
MODEL="claude-opus-5-5"
EFFORT=""   # empty — keep the original's effort
CHECK=0

usage() {
  cat <<'USAGE'
Usage: scripts/sync-saving-agents.sh [--model ID] [--effort LEVEL] [--check]

  --model ID      the twins' model (claude-opus-5-5 by default).
                  Out of Opus limits — regenerate on another one:
                  --model claude-sonnet-5, --model claude-fable-5-1
  --effort LEVEL  low | medium | high | xhigh | max; without the flag each role
                  keeps its own effort from the original
  --check         write nothing, only report whether the twins have diverged
                  from the originals (exit code 1 if they have)
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --model)  MODEL="${2:?--model requires a value}"; shift 2 ;;
    --effort) EFFORT="${2:?--effort requires a value}"; shift 2 ;;
    --check)  CHECK=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown argument: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

# A twin = the original with rewritten front-matter. The role body is left untouched:
# the instruction to the analyst is the same whichever model it runs on.
render() {
  awk -v role="$1" -v suffix="$SUFFIX" -v model="$MODEL" -v effort="$EFFORT" '
    BEGIN { fm = 0; seen_model = 0; seen_effort = 0 }
    NR == 1 && $0 == "---" { fm = 1; print; next }
    fm == 1 && $0 == "---" {
      if (!seen_model)  print "model: " model
      if (!seen_effort && effort != "") print "effort: " effort
      print "---"
      print ""
      print "<!-- Generated by scripts/sync-saving-agents.sh from " role ".md — edit the original. -->"
      fm = 2
      next
    }
    fm == 1 {
      if ($0 ~ /^name:/)   { print "name: " role "-" suffix; next }
      if ($0 ~ /^model:/)  { print "model: " model; seen_model = 1; next }
      if ($0 ~ /^effort:/) {
        seen_effort = 1
        if (effort != "") print "effort: " effort; else print
        next
      }
      if ($0 ~ /^description:/) {
        sub(/^description: */, "")
        print "description: Twin of role " role " on model " model " for the /feature-" suffix " command; not used by the regular pipeline. " $0
        next
      }
      print; next
    }
    { print }
  ' "$2"
}

changed=0
for role in "${ROLES[@]}"; do
  src="$AGENTS/$role.md"
  dst="$AGENTS/$role-$SUFFIX.md"
  [ -f "$src" ] || { printf 'no original: %s\n' "$src" >&2; exit 1; }

  if [ "$CHECK" -eq 1 ]; then
    if ! render "$role" "$src" | diff -q - "$dst" >/dev/null 2>&1; then
      printf 'diverged: %s\n' "$dst"
      changed=$((changed + 1))
    fi
  else
    render "$role" "$src" > "$dst"
  fi
done

if [ "$CHECK" -eq 1 ]; then
  if [ "$changed" -gt 0 ]; then
    printf '\nRegenerate: scripts/sync-saving-agents.sh --model %s\n' "$MODEL"
    exit 1
  fi
  printf 'twins match the originals (%s)\n' "$MODEL"
  exit 0
fi

printf 'roles: %d → model %s, effort %s\n' \
  "${#ROLES[@]}" "$MODEL" "${EFFORT:-from the originals}"
printf 'pipeline command: /feature-%s\n' "$SUFFIX"
